name: Deploy to EC2

on:
  push:
    branches:
      - main  # Este flujo se ejecuta al hacer push al branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Run deploy.sh on EC2
      run: |
        echo "🔐 Conectando a EC2 y ejecutando el script de despliegue..."
        ssh -o StrictHostKeyChecking=no ubuntu@18.222.145.75 << 'EOF'
          chmod +x ~/demo_inapptik/scripts/deploy.sh
          ~/demo_inapptik/scripts/deploy.sh
        EOF
