name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up SSH access to EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Run deploy script on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.222.145.75 << 'EOF'
          cd ~/demo_inapptik || exit 1
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh || exit 1
        EOF
