name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 prueba_inapptik.pem
          ssh -i prueba_inapptik.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'bash deploy.sh'
